import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Title and description metadata for the application
export const metadata: Metadata = {
  title: "NextJS Basic App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Objekt mit Pfaden und Titeln für die Navigation
  const navItems = [
    { href: "/", title: "Home" },
    { href: "/about", title: "About" },
    { href: "/projects", title: "Projects" },
    { href: "/blog", title: "Blog" },
    { href: "/books", title: "Books" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-rose-500 text-white mb-5 p-5 flex flex-col items-center">
          <h1 className="mb-5">
            <Link href={"/"} className="font-bold text-3xl">This is the Header</Link>
          </h1>
          <ul className="flex gap-4">
            {navItems.map((item, index) => (
              <li key={index}>
                <Link
                  href={item.href}
                  className="p-3 border-2 border-black rounded-xl hover:cursor-pointer hover:text-black"
                >
                  {item.title}
                </Link>
              </li>
            ))}
          </ul>
        </header>
        {children}
        <footer className="bg-rose-500 text-white mt-5 p-5">
          This is the Footer
        </footer>
      </body>
    </html>
  );
}
